Design fix
qaseem-aslam-brainx/CSS pull request #1
Opened 2020-09-22 12:03 UTC by qaseem-aslam-brainx

2020-09-23 05:15 UTC, sobanakram requested changes

2020-09-23 05:15 UTC, sobanakram commented on sponser_dashboard.html
> +        <link rel="stylesheet" href="sponsor-dashboard-style.css">
We don't need to add `style` in file name,
better way is to create folder for css

2020-09-23 05:15 UTC, sobanakram commented on sponser_dashboard.html
> +            <div class="circleoutline">
use `-` for classes names.
and outline is different then border.

2020-09-23 05:15 UTC, sobanakram commented on sponser_dashboard.html
> +                    <span id="sign-out">Sign Out</span><br>
using style in css class name is not necessary.

2020-09-23 05:15 UTC, sobanakram commented on sponser_dashboard.html
> +                <h1 id="fair-heading">Virtual Fair</h1>
avoid adding `id` if we don't need it.

2020-09-23 05:15 UTC, sobanakram commented on sponser_dashboard.html
> +                    <li><a href="#" class="sponsor-style">Sponser</a></li>
separate class is used to show active tab.
`active` adding this class should make active and change styling

2020-09-23 05:15 UTC, sobanakram commented on sponser_dashboard.html
> +                            <td><img style="margin-top: 5px;" src="logo.png" ></td>
Remove inline styling.

2020-09-23 05:15 UTC, sobanakram commented on sponser_dashboard.html
> +                            <td><span class="status-active">Active</span></td>
Use two separate classes `status` `active`.

2020-09-23 05:15 UTC, sobanakram commented on sponsor-dashboard-style.css
> +#fair-heading{
Avoid styling based in `id`

2020-09-23 05:15 UTC, sobanakram commented on sponsor-dashboard-style.css
> +    padding: 10px 10px 10px 10px;
we can use shorthand version like `padding: 10px;`

2020-09-23 05:15 UTC, sobanakram commented on sponsor-dashboard-style.css
> +    padding: 0% 20% 0% 20%;
shorthand version `padding: 0% 20%;`

2020-09-23 05:15 UTC, sobanakram commented on sponsor-dashboard-style.css
> +    padding: 13px 0px 0px 0px;
instead of adding zero padding, just use `padding-top` means specific

2020-09-23 05:20 UTC, sobanakram commented
@qaseem-aslam-brainx 
Points to note:
1. Indent code properly, you can use Vs Code to indent using keyboard shortcut.
2. avoid writing css classes with specific text which looks like can be changed, css should be independent of html.
3. use lowercase for colors and look into css variables.

2020-09-23 07:13 UTC, qaseem-aslam-brainx commented
@sobanakram 
Is the 2nd point about class names like "fair-heading", "sponsor-list-table" etc. ?

2020-09-23 09:08 UTC, sobanakram requested changes

2020-09-23 09:08 UTC, sobanakram commented on css/sponsor-dashboard.css
> +:root {
css variables should be in base style file which will be available in all views.

2020-09-23 09:08 UTC, sobanakram commented on css/sponsor-dashboard.css
> +.active{
We should scope these with status as this is only concerned with status.
like `.status.active`

2020-09-23 09:08 UTC, sobanakram commented on css/event-dashboard.css
> +.container{
add this to common css file

2020-09-23 09:08 UTC, sobanakram commented on css/nav-bar.css
> +* {
we can keep it as common css file and just `style.css` name works.

2020-09-25 07:28 UTC, sobanakram approved these changes

2020-09-25 07:31 UTC, merged